on: [push, pull_request]

jobs:
  sounds_good:
    runs-on: ubuntu-latest
    name: Does this change sound good?
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Does this change sound good?
        id: code_sound
        uses: MarkusH/code-sound@6c9cc3db45dbafea570719c03454d52ad59cef2f
      - uses: actions/upload-artifact@v1
        with:
          name: code-sound.ogg
          path: .code_sound/outfile.ogg
