on: [push, pull_request]

jobs:
  sounds_good:
    runs-on: ubuntu-latest
    name: Does this change sound good?
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Does this change sound good?
      #   id: code_sound
      #   uses: MarkusH/code-sound@4c16b1f7e865a6e7ac5cb18b6a3eed8cd805d717
      - name: Does this change sound good?
        id: code_sound
        uses: ./
      - uses: actions/upload-artifact@v1
        with:
          name: code-sound.ogg
          path: .code_sound/outfile.ogg
